name: Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "45 8 * * 1"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.9.2-focal
          - swift:6.0-noble
          - swift:6.2-jammy
    container: ${{ matrix.image }}
    steps:
      - name: Install SQLite
        run: |
          apt-get update
          apt-get -y install libsqlite3-dev
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
      - name: Run Tests
        run: swift test
  nextstep:
    runs-on: macos-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Xcode Project
        run: xcodebuild -project ZeeQL3.xcodeproj -scheme ZeeQL
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
#      - name: Run Package Tests
#        run: swift test
      - name: Run Xcode Tests
        run: xcodebuild -project ZeeQL3.xcodeproj -scheme ZeeQL test
